name: Bug Report
description: Report broken or unexpected behavior
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report!

        > [!NOTE]
        > This form is for reporting reproducible bugs.
        > For questions or general support, please use [GitHub Discussions](https://github.com/D4isDAVID/dxm/discussions) or join the [Discord server](https://discord.gg/rdjpS2K8hC).

        > [!WARNING]
        > If you believe you have found a security vulnerability, **DO NOT** open an issue.
        > Please follow the [Security Policy](https://github.com/D4isDAVID/dxm/security/policy) instead.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: What steps can someone take to reproduce this bug?
      placeholder: |
        1. Using ...
        2. Do ...
        3. Then use ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened when taking the steps?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened when taking the steps?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Optional additional information such as screenshots, videos, or links.

  - type: input
    id: version
    attributes:
      label: Project Version
      description: What version of the project are you currently using? (use `dxm -V` to find out)
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using dxm on?
      placeholder: e.g. Windows 11
    validations:
      required: true
