name: Feature Request
description: Suggest new functionality or improvements
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This form is for suggesting new features or improvements.
        > For questions or general support, please use [GitHub Discussions](https://github.com/D4isDAVID/dxm/discussions) or join the [Discord server](https://discord.gg/rdjpS2K8hC).

        > [!WARNING]
        > If you believe you have found a security vulnerability, **DO NOT** open an issue.
        > Please follow the [Security Policy](https://github.com/D4isDAVID/dxm/security/policy) instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem are you trying to solve, or what use case is missing?
      placeholder: |
        I'm frustrated that ...
        It would be helpful if ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What feature or improvement would you like to see?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternative solutions or features have you considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Optional additional information such as screenshots, videos, or links.
